# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protoDefs/PbCurveList.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'protoDefs/PbCurveList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotoDefs/PbCurveList.proto\x12\x0bpbCurveList\"d\n\x0bPbCurveList\x12\x16\n\x0epointAttrNames\x18\x06 \x03(\t\x12\x16\n\x0e\x63urveAttrNames\x18\x07 \x03(\t\x12%\n\tcurveList\x18\x05 \x03(\x0b\x32\x12.pbCurveList.Curve\"M\n\x05\x43urve\x12\n\n\x02id\x18\x04 \x02(\r\x12%\n\tpointList\x18\x03 \x03(\x0b\x32\x12.pbCurveList.Point\x12\x11\n\tvalueList\x18\x02 \x03(\x02\"\x1a\n\x05Point\x12\x11\n\tvalueList\x18\x01 \x03(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoDefs.PbCurveList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PBCURVELIST']._serialized_start=44
  _globals['_PBCURVELIST']._serialized_end=144
  _globals['_CURVE']._serialized_start=146
  _globals['_CURVE']._serialized_end=223
  _globals['_POINT']._serialized_start=225
  _globals['_POINT']._serialized_end=251
# @@protoc_insertion_point(module_scope)
