# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protoDefs/RLE.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'protoDefs/RLE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protoDefs/RLE.proto\x12\x0bimageLabels\"0\n\x0bImageLabels\x12!\n\x07rowList\x18\x01 \x03(\x0b\x32\x10.imageLabels.Row\")\n\x03Row\x12\"\n\x03row\x18\x01 \x03(\x0b\x32\x15.imageLabels.LabelRun\"8\n\x08LabelRun\x12\r\n\x05start\x18\x01 \x02(\x05\x12\x0e\n\x06length\x18\x02 \x02(\x05\x12\r\n\x05label\x18\x03 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protoDefs.RLE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGELABELS']._serialized_start=36
  _globals['_IMAGELABELS']._serialized_end=84
  _globals['_ROW']._serialized_start=86
  _globals['_ROW']._serialized_end=127
  _globals['_LABELRUN']._serialized_start=129
  _globals['_LABELRUN']._serialized_end=185
# @@protoc_insertion_point(module_scope)
